# Generated by Django 3.1.4 on 2021-01-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='cpu_img',
            field=models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
