# Generated by Django 3.1.4 on 2021-01-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_cpu_cpu_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='price',
            field=models.CharField(help_text='Введите цену процессора', max_length=20, null=True, verbose_name='Цена процессора'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='motherboard_img',
            field=models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='price',
            field=models.CharField(help_text='Введите цену материнской платы', max_length=20, null=True, verbose_name='Цена материнской платы'),
        ),
    ]
