# Generated by Django 3.1.4 on 2021-01-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210112_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='generation',
            field=models.CharField(help_text='Введите поколение процессора', max_length=50, null=True, verbose_name='Поколение процессора'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='yearrelease',
            field=models.IntegerField(choices=[('1990', '1990'), ('1991', '1991'), ('1992', '1992')], null=True),
        ),
    ]
