# Generated by Django 3.1.4 on 2021-01-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210112_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='freq',
        ),
        migrations.AddField(
            model_name='cpu',
            name='basefreq',
            field=models.CharField(help_text='Введите базовую частоту процессора', max_length=20, null=True, verbose_name='Базовая частота процессора'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='cacheL1',
            field=models.CharField(help_text='Введите объем кэша L1', max_length=20, null=True, verbose_name='Кэш L1'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='cacheL2',
            field=models.CharField(help_text='Введите объем кэша L2', max_length=20, null=True, verbose_name='Кэш L2'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='cacheL3',
            field=models.CharField(help_text='Введите объем кэша L3', max_length=20, null=True, verbose_name='Кэш L3'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='maxfreq',
            field=models.CharField(help_text='Введите максимальную частоту процессора', max_length=20, null=True, verbose_name='Максимальная частота процессора'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='yearrelease',
            field=models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], help_text='Выберите дату релиза процессора', null=True, verbose_name='Год релиза'),
        ),
    ]
