# Generated by Django 3.1.4 on 2021-01-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210113_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reviewcpu',
            name='rate',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Оцените товар', null=True, verbose_name='Оценка'),
        ),
    ]
