# Generated by Django 3.1.4 on 2021-01-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20210113_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='numcore',
            field=models.IntegerField(help_text='Введите количество ядер', null=True, verbose_name='Количество ядер'),
        ),
    ]
