# Generated by Django 3.1.4 on 2021-01-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20210113_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='countrate',
            field=models.IntegerField(null=True),
        ),
    ]
