# Generated by Django 3.1.4 on 2021-01-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_cpu_countrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='countrate',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='rate',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
