# Generated by Django 3.1.4 on 2021-01-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20210113_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='countrate',
            field=models.IntegerField(default=2021, null=True),
        ),
    ]
