# Generated by Django 3.1.4 on 2021-01-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20210113_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='countrate',
            field=models.IntegerField(choices=[(0, 0)], default=2021, null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='rate',
            field=models.IntegerField(choices=[(0, 0)], default=2021, null=True),
        ),
    ]
