# Generated by Django 3.1.4 on 2021-01-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20210113_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='avrrate',
            field=models.IntegerField(null=True),
        ),
    ]
