# Generated by Django 3.1.4 on 2021-01-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_cpu_avrrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='avrrate',
            field=models.FloatField(null=True),
        ),
    ]
