# Generated by Django 3.1.4 on 2021-01-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20210113_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboard',
            name='avrrate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='countrate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='rate',
            field=models.IntegerField(null=True),
        ),
    ]
