# Generated by Django 3.1.4 on 2021-01-14 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20210114_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpu',
            options={'verbose_name': 'Процессор', 'verbose_name_plural': 'Процессоры'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterField(
            model_name='cpu',
            name='avrrate',
            field=models.FloatField(null=True, verbose_name='Средняя оценка'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='countrate',
            field=models.IntegerField(null=True, verbose_name='Количество оценок'),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='rate',
            field=models.IntegerField(null=True, verbose_name='Общая оценка'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='avrrate',
            field=models.FloatField(null=True, verbose_name='Средняя оценка'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='countrate',
            field=models.IntegerField(null=True, verbose_name='Количество оценок'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='cpu',
            field=models.ManyToManyField(help_text='Выберите подходящий процессор', to='catalog.CPU', verbose_name='Подходящие процессоры'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='rate',
            field=models.IntegerField(null=True, verbose_name='Общая оценка'),
        ),
    ]
